### PR TITLE
Feat: #12 player healthbar

### LINKED ISSUE #12: Player healthbar
BLOCKED BY: https://github.com/SillyBusinessInc/SillyBusinessGame/issues/7

The player should have a health bar. If it reach 0 you are dead.
You then can just respawn on a designated spawn platform (which you spawn also at the start of the game)

### PR DESCRIPTION
**Pull request by PimMiii**
## Purpose of this PR:
Add a healthbar UI element to the game.

The FollowingEnemy has received a new AttackingState, this does configurable damage when the enemy is in a configurable range and has a configurable cooldown

## How to test:
Open up the PlayerHealthbarScene and hit run.
You should see 3 heart in the top left corner of the screen.
There is a testscript available on the TestScript GameObject, this allows you to do 1, 10 , or 100 damage to the player.

To test the FollowingEnemy attack simply run the game, and make sure to walk into the cone of vision of the enemy.
Once the enemy is in range it will do 25 damage (default, but configurable) and it should then not attack untill the cooldown is over. 

### links: 
closes #12 

### note:
This can be improved by making use of the soon to be merged event system, and will have to make use of the new stat system.

### CODE REVIEW

**Review by WantToBeeMe — CHANGES_REQUESTED** [review]
Cool, it works for me.
However, the enemy is pushing me off the map 😅
Maybe add something that the enemy stands still in the attack state. 
This automatically fixes the problem

**Comment by MustacheAltun** [comment]
the code looks good to me apart from the bug i saw at dirk.

**Comment by PimMiii** [comment]
updated to fix mentioned bug.
attackCooldown now keeps the enemy in AttackingState without being able to attack. This means it can't move for this period. At the end of the cooldown, state is set to FollowingState.

**Comment by PimMiii** [comment]
Fixed merge conflict

**Review by WantToBeeMe — APPROVED** [review]

**Pull request merged**
